# Generated by Django 5.2.2 on 2025-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_contact_doctor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatioendDoctorMapping',
            new_name='PatientDoctorMapping',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor'),
        ),
    ]
