import type { User, Doctor, Patient, PatientDoctorMapping } from "./types"

// Mock users data
export const mockUsers: Record<string, User> = {
  "user-1": {
    id: "user-1",
    email: "john@example.com",
    name: "John Doe",
    role: "patient",
    phone: "555-0101",
    createdAt: new Date("2024-01-15"),
  },
  "user-2": {
    id: "user-2",
    email: "sarah@example.com",
    name: "Dr. Sarah Johnson",
    role: "doctor",
    phone: "555-0102",
    specialization: "Cardiology",
    createdAt: new Date("2023-06-20"),
  },
  "user-3": {
    id: "user-3",
    email: "admin@example.com",
    name: "Admin User",
    role: "admin",
    phone: "555-0103",
    createdAt: new Date("2023-01-01"),
  },
  "user-4": {
    id: "user-4",
    email: "mike@example.com",
    name: "Mike Smith",
    role: "patient",
    phone: "555-0104",
    createdAt: new Date("2024-02-10"),
  },
  "user-5": {
    id: "user-5",
    email: "dr.alex@example.com",
    name: "Dr. Alex Brown",
    role: "doctor",
    phone: "555-0105",
    specialization: "General Medicine",
    createdAt: new Date("2023-08-05"),
  },
}

export const mockDoctors: Doctor[] = [
  {
    id: "user-2",
    email: "sarah@example.com",
    name: "Dr. Sarah Johnson",
    role: "doctor",
    phone: "555-0102",
    specialization: "Cardiology",
    licenseNumber: "LIC-001",
    experience: 12,
    availability: "available",
    patients: ["user-1", "user-4"],
    createdAt: new Date("2023-06-20"),
  },
  {
    id: "user-5",
    email: "dr.alex@example.com",
    name: "Dr. Alex Brown",
    role: "doctor",
    phone: "555-0105",
    specialization: "General Medicine",
    licenseNumber: "LIC-002",
    experience: 8,
    availability: "available",
    patients: ["user-1"],
    createdAt: new Date("2023-08-05"),
  },
  {
    id: "user-6",
    email: "dr.emma@example.com",
    name: "Dr. Emma Wilson",
    role: "doctor",
    phone: "555-0106",
    specialization: "Dermatology",
    licenseNumber: "LIC-003",
    experience: 10,
    availability: "unavailable",
    patients: [],
    createdAt: new Date("2024-01-12"),
  },
]

export const mockPatients: Patient[] = [
  {
    id: "user-1",
    email: "john@example.com",
    name: "John Doe",
    role: "patient",
    phone: "555-0101",
    dateOfBirth: "1985-05-15",
    bloodGroup: "O+",
    medicalHistory: "Hypertension",
    currentSymptoms: ["chest pain", "shortness of breath"],
    assignedDoctors: ["user-2", "user-5"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user-4",
    email: "mike@example.com",
    name: "Mike Smith",
    role: "patient",
    phone: "555-0104",
    dateOfBirth: "1992-03-22",
    bloodGroup: "A+",
    medicalHistory: "Allergies",
    currentSymptoms: ["skin rash", "itching"],
    assignedDoctors: ["user-2"],
    createdAt: new Date("2024-02-10"),
  },
]

export const mockMappings: PatientDoctorMapping[] = [
  {
    id: "mapping-1",
    patientId: "user-1",
    doctorId: "user-2",
    symptoms: ["chest pain", "shortness of breath"],
    status: "active",
    assignedDate: new Date("2024-01-20"),
    notes: "Cardiac checkup required",
  },
  {
    id: "mapping-2",
    patientId: "user-1",
    doctorId: "user-5",
    symptoms: ["general consultation"],
    status: "active",
    assignedDate: new Date("2024-01-25"),
    notes: "Regular consultation",
  },
  {
    id: "mapping-3",
    patientId: "user-4",
    doctorId: "user-2",
    symptoms: ["skin rash", "itching"],
    status: "active",
    assignedDate: new Date("2024-02-12"),
    notes: "Referral from general practitioner",
  },
]
